# Generated by Django 6.0.3 on 2026-04-04 14:48

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="StockMaster",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("ticker", models.CharField(max_length=20, unique=True)),
                ("name_kr", models.CharField(max_length=500)),
                ("market", models.CharField(max_length=10)),
                (
                    "index_type",
                    models.CharField(
                        blank=True,
                        choices=[
                            ("K200", "코스피 200"),
                            ("Q150", "코스닥 150"),
                            ("N100", "나스닥 100"),
                        ],
                        db_index=True,
                        help_text="편입된 주요 지수를 선택하세요.",
                        max_length=10,
                        null=True,
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="StockAnalysisLatest",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("t_signal", models.CharField(default="gray", max_length=10)),
                ("n_signal", models.CharField(default="gray", max_length=10)),
                ("c_signal", models.CharField(default="gray", max_length=10)),
                ("p_name", models.CharField(default="대기중", max_length=50)),
                ("up_days", models.IntegerField(default=0)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "stock",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="latest_analysis",
                        to="stock.stockmaster",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="MyTrackedStock",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "stock",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="stock.stockmaster",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="StockAnalysisHistory",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("date", models.DateField(db_index=True)),
                ("t_signal", models.CharField(default="gray", max_length=10)),
                ("n_signal", models.CharField(default="gray", max_length=10)),
                ("c_signal", models.CharField(default="gray", max_length=10)),
                ("p_name", models.CharField(default="대기중", max_length=50)),
                ("up_days", models.IntegerField(default=0)),
                (
                    "stock",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="analysis_history",
                        to="stock.stockmaster",
                    ),
                ),
            ],
            options={
                "ordering": ["-date"],
                "unique_together": {("stock", "date")},
            },
        ),
    ]
