# Generated by Django 6.0.3 on 2026-04-05 12:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("stock", "0002_signalcode"),
    ]

    operations = [
        migrations.AddField(
            model_name="stockanalysishistory",
            name="signal_code",
            field=models.CharField(
                default="d01", max_length=10, verbose_name="공통 코드"
            ),
        ),
        migrations.AddField(
            model_name="stockanalysislatest",
            name="signal_code",
            field=models.CharField(
                default="d01", max_length=10, verbose_name="공통 코드"
            ),
        ),
    ]
