# Generated by Django 6.0.3 on 2026-04-07 13:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("stock", "0005_alter_stockmaster_exchange_alter_stockmaster_market_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="stockmaster",
            name="updated_at",
            field=models.DateTimeField(auto_now=True, verbose_name="수정 일시"),
        ),
    ]
