# Generated by Django 6.0.3 on 2026-04-09 15:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("stock", "0006_stockmaster_updated_at"),
    ]

    operations = [
        migrations.AddField(
            model_name="stockanalysislatest",
            name="p_code",
            field=models.CharField(
                default="p04", max_length=10, verbose_name="패턴 코드"
            ),
        ),
    ]
