# Generated by Django 6.0.3 on 2026-05-12 12:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("stock", "0012_alter_stockanalysislatest_options_and_more"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="coinanalysislatest",
            options={
                "verbose_name": "코인 분석 결과",
                "verbose_name_plural": "코인 분석 결과 목록",
            },
        ),
    ]
