"""
Django settings for stocks project.

Generated by 'django-admin startproject' using Django 5.0.9.
"""

import os
from pathlib import Path
import dj_database_url
from dotenv import load_dotenv

# .env 파일의 변수들을 시스템 환경변수로 등록
load_dotenv()

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))

# 1. 환경 분리: 구글 클라우드 환경인지 확인
IS_CLOUD_RUN = os.environ.get('K_SERVICE') is not None

if IS_CLOUD_RUN:
    # ------------------ [운영 환경 (Google Cloud Run)] ------------------
    DEBUG = False
    ALLOWED_HOSTS = ['*']  
    
    # HTTPS 보안 설정 (운영 환경 필수)
    SECURE_PROXY_SSL_HEADER = ('HTTP_X_FORWARDED_PROTO', 'https')
    SECURE_SSL_REDIRECT = True
    SESSION_COOKIE_SECURE = True
    CSRF_COOKIE_SECURE = True
    
    # Cloud Run 도메인 허용
    CSRF_TRUSTED_ORIGINS = [
        'https://stocks-892926059541.us-west1.run.app',
        'https://stocks-lmiyo3u4ya-uw.a.run.app',
        'https://*.run.app', 
    ]
else:
    # ------------------ [로컬 개발 환경] ------------------
    DEBUG = True
    ALLOWED_HOSTS = ['localhost', '127.0.0.1', '*']
    
    # 로컬 강제 HTTPS 전환 해제 (로컬 에러 방지 핵심)
    SECURE_SSL_REDIRECT = False
    SESSION_COOKIE_SECURE = False
    CSRF_COOKIE_SECURE = False

    # 로컬 접속 주소 허용
    CSRF_TRUSTED_ORIGINS = [
        'http://127.0.0.1:8000',
        'http://localhost:8000',
    ]

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = "django-insecure-z_-z^##y@my*$lzib=19e_flu7@%5ys)ptt34%(jt6f^db99us"
# 환경변수에서 SECRET_KEY를 불러오도록 변경 (없을 경우 로컬용 임시 키 사용)
SECRET_KEY = os.environ.get('DJANGO_SECRET_KEY', 'django-insecure-z_-z^##y@my*$lzib=19e_flu7@%5ys)ptt34%(jt6f^db99us')

# Application definition
INSTALLED_APPS = [
    'import_export',
    'stock.apps.StocksConfig',
    "django.contrib.admin",
    "django.contrib.auth",
    "django.contrib.contenttypes",
    "django.contrib.sessions",
    "django.contrib.messages",
    "django.contrib.staticfiles",
]

MIDDLEWARE = [
    "django.middleware.security.SecurityMiddleware",
    "whitenoise.middleware.WhiteNoiseMiddleware", # WhiteNoise 정적 파일 서빙
    "django.contrib.sessions.middleware.SessionMiddleware",
    "django.middleware.common.CommonMiddleware",
    "django.middleware.csrf.CsrfViewMiddleware",
    "django.contrib.auth.middleware.AuthenticationMiddleware",
    "django.contrib.messages.middleware.MessageMiddleware",
    "django.middleware.clickjacking.XFrameOptionsMiddleware",
]

ROOT_URLCONF = "stocks.urls"

TEMPLATES = [
    {
        "BACKEND": "django.template.backends.django.DjangoTemplates",
        "DIRS": [os.path.join(BASE_DIR, 'templates')], # 템플릿 경로 명시
        "APP_DIRS": True,
        "OPTIONS": {
            "context_processors": [
                "django.template.context_processors.debug",
                "django.template.context_processors.request",
                "django.contrib.auth.context_processors.auth",
                "django.contrib.messages.context_processors.messages",
            ],
        },
    },
]

WSGI_APPLICATION = "stocks.wsgi.application"

# Database
DATABASES = {
    'default': {
        'ENGINE': 'django.db.backends.postgresql',
        'NAME': 'defaultdb',
        'USER': os.environ.get('DB_USER', 'avnadmin'),
        'PASSWORD': os.environ.get('DB_PASSWORD', ''),  # 환경변수로 안전하게 관리
        'HOST': os.environ.get('DB_HOST', 'pg-31479f22-batteryz1999-stocks.d.aivencloud.com'),
        'PORT': '22915',
        'OPTIONS': {
            'sslmode': 'require',  # 🚀 이 부분이 반드시 있어야 합니다!
        },
    }
}

# Password validation
AUTH_PASSWORD_VALIDATORS = [
    {"NAME": "django.contrib.auth.password_validation.UserAttributeSimilarityValidator",},
    {"NAME": "django.contrib.auth.password_validation.MinimumLengthValidator",},
    {"NAME": "django.contrib.auth.password_validation.CommonPasswordValidator",},
    {"NAME": "django.contrib.auth.password_validation.NumericPasswordValidator",},
]

# Internationalization
LANGUAGE_CODE = 'ko-kr'
TIME_ZONE = 'Asia/Seoul'
USE_I18N = True
USE_TZ = True

# Default primary key field type
DEFAULT_AUTO_FIELD = "django.db.models.BigAutoField"

# ------------------ [정적 파일(Static) 및 미디어(Media) 설정] ------------------

# 미디어 파일 설정 (특정 PC 절대경로 대신 BASE_DIR 기반 동적 할당으로 수정)
MEDIA_URL = '/media/'
MEDIA_ROOT = os.path.join(BASE_DIR, 'media')

# 정적 파일(CSS, JS, 이미지 등)의 기본 URL
STATIC_URL = '/static/'

# 배포 시 collectstatic 명령어로 정적 파일들이 모이는 폴더 위치
STATIC_ROOT = os.path.join(BASE_DIR, 'staticfiles')

# 개발 시 정적 파일들이 위치한 폴더
STATICFILES_DIRS = [
    os.path.join(BASE_DIR, 'static'),
]

# WhiteNoise 정적 파일 캐싱 스토리지 적용
STATICFILES_STORAGE = "whitenoise.storage.CompressedManifestStaticFilesStorage"