# Generated by Django 6.0.3 on 2026-04-05 12:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("stock", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="SignalCode",
            fields=[
                (
                    "code",
                    models.CharField(
                        max_length=10,
                        primary_key=True,
                        serialize=False,
                        verbose_name="시그널 코드",
                    ),
                ),
                ("name", models.CharField(max_length=50, verbose_name="시그널 명칭")),
                (
                    "description",
                    models.CharField(max_length=200, verbose_name="의미 및 설명"),
                ),
            ],
        ),
    ]
