# Generated by Django 6.0.3 on 2026-04-06 12:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("stock", "0003_stockanalysishistory_signal_code_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="stockmaster",
            name="exchange",
            field=models.CharField(
                blank=True,
                help_text="상세 거래소 (NASDAQ, NYSE, KOSPI 등)",
                max_length=50,
                null=True,
            ),
        ),
    ]
