# Generated by Django 6.0.3 on 2026-04-07 13:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("stock", "0004_stockmaster_exchange"),
    ]

    operations = [
        migrations.AlterField(
            model_name="stockmaster",
            name="exchange",
            field=models.CharField(
                blank=True,
                choices=[
                    ("KOSPI", "코스피 (KOSPI)"),
                    ("KOSDAQ", "코스닥 (KOSDAQ)"),
                    ("NASDAQ", "나스닥 (NASDAQ)"),
                    ("NYSE", "뉴욕증권거래소 (NYSE)"),
                    ("AMEX", "아멕스 (AMEX)"),
                    ("COIN", "암호화폐 (COIN)"),
                ],
                max_length=50,
                null=True,
            ),
        ),
        migrations.AlterField(
            model_name="stockmaster",
            name="market",
            field=models.CharField(
                choices=[
                    ("KR", "한국 (KR)"),
                    ("US", "미국 (US)"),
                    ("COIN", "암호화폐 (COIN)"),
                ],
                max_length=50,
            ),
        ),
        migrations.AddConstraint(
            model_name="stockmaster",
            constraint=models.UniqueConstraint(
                fields=("ticker", "market"), name="unique_stock_ticker_market"
            ),
        ),
    ]
