# Generated by Django 6.0.3 on 2026-04-10 13:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("stock", "0007_stockanalysislatest_p_code"),
    ]

    operations = [
        migrations.AddField(
            model_name="stockanalysishistory",
            name="p_code",
            field=models.CharField(
                default="p04", max_length=10, verbose_name="패턴 코드"
            ),
        ),
    ]
