# Generated by Django 6.0.3 on 2026-04-20 12:44

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("stock", "0008_stockanalysishistory_p_code"),
    ]

    operations = [
        migrations.CreateModel(
            name="StockDailyChart",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("date", models.DateField(verbose_name="거래 일자")),
                (
                    "open_price",
                    models.DecimalField(
                        decimal_places=4, max_digits=20, verbose_name="시가"
                    ),
                ),
                (
                    "high_price",
                    models.DecimalField(
                        decimal_places=4, max_digits=20, verbose_name="고가"
                    ),
                ),
                (
                    "low_price",
                    models.DecimalField(
                        decimal_places=4, max_digits=20, verbose_name="저가"
                    ),
                ),
                (
                    "close_price",
                    models.DecimalField(
                        decimal_places=4, max_digits=20, verbose_name="종가"
                    ),
                ),
                (
                    "adj_close",
                    models.DecimalField(
                        decimal_places=4, max_digits=20, verbose_name="수정 종가"
                    ),
                ),
                ("volume", models.BigIntegerField(verbose_name="거래량")),
            ],
            options={
                "verbose_name": "일별 차트 데이터",
                "verbose_name_plural": "일별 차트 데이터 목록",
            },
        ),
        migrations.AlterUniqueTogether(
            name="stockanalysishistory",
            unique_together=set(),
        ),
        migrations.AlterField(
            model_name="stockanalysishistory",
            name="p_code",
            field=models.CharField(
                default="p90", max_length=10, verbose_name="패턴 코드"
            ),
        ),
        migrations.AddConstraint(
            model_name="stockanalysishistory",
            constraint=models.UniqueConstraint(
                fields=("stock", "date"), name="unique_stock_analysis_history"
            ),
        ),
        migrations.AddField(
            model_name="stockdailychart",
            name="stock",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="daily_charts",
                to="stock.stockmaster",
                to_field="ticker",
            ),
        ),
        migrations.AddIndex(
            model_name="stockdailychart",
            index=models.Index(
                fields=["stock", "-date"], name="stock_stock_stock_i_ec9bbd_idx"
            ),
        ),
        migrations.AddConstraint(
            model_name="stockdailychart",
            constraint=models.UniqueConstraint(
                fields=("stock", "date"), name="unique_stock_date"
            ),
        ),
    ]
