# Generated by Django 6.0.3 on 2026-04-25 13:50

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("stock", "0009_stockdailychart_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="SignalCode2",
            fields=[
                (
                    "code",
                    models.CharField(
                        max_length=10,
                        primary_key=True,
                        serialize=False,
                        verbose_name="시그널 코드",
                    ),
                ),
                ("name", models.CharField(max_length=50, verbose_name="시그널 명칭")),
                (
                    "description",
                    models.CharField(max_length=200, verbose_name="의미 및 설명"),
                ),
            ],
        ),
        migrations.CreateModel(
            name="StockAnalysisLatest2",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "analyzed_date",
                    models.DateField(blank=True, null=True, verbose_name="분석 기준일"),
                ),
                (
                    "close_price",
                    models.DecimalField(
                        blank=True,
                        decimal_places=4,
                        max_digits=20,
                        null=True,
                        verbose_name="종가",
                    ),
                ),
                (
                    "volume",
                    models.BigIntegerField(
                        blank=True, null=True, verbose_name="거래량"
                    ),
                ),
                (
                    "vol_ratio",
                    models.FloatField(
                        blank=True, null=True, verbose_name="거래량 배수"
                    ),
                ),
                (
                    "change_rate",
                    models.FloatField(blank=True, null=True, verbose_name="등락률(%)"),
                ),
                ("t_signal", models.CharField(default="gray", max_length=10)),
                ("n_signal", models.CharField(default="gray", max_length=10)),
                ("c_signal", models.CharField(default="gray", max_length=10)),
                (
                    "p_code",
                    models.CharField(
                        default="p04", max_length=10, verbose_name="패턴 코드"
                    ),
                ),
                ("p_name", models.CharField(default="대기중", max_length=50)),
                ("up_days", models.IntegerField(default=0)),
                (
                    "signal",
                    models.CharField(
                        default="대기중", max_length=100, verbose_name="시그널 텍스트"
                    ),
                ),
                ("priority", models.IntegerField(default=0, verbose_name="우선순위")),
                (
                    "action",
                    models.TextField(blank=True, null=True, verbose_name="행동 지침"),
                ),
                (
                    "supertrend_direction",
                    models.IntegerField(
                        blank=True, null=True, verbose_name="방향(1/-1)"
                    ),
                ),
                (
                    "supertrend_value",
                    models.DecimalField(
                        blank=True, decimal_places=4, max_digits=20, null=True
                    ),
                ),
                ("wt1", models.FloatField(blank=True, null=True)),
                ("wt2", models.FloatField(blank=True, null=True)),
                ("wt_cross_up", models.BooleanField(default=False)),
                ("wt_cross_down", models.BooleanField(default=False)),
                ("wt_oversold", models.BooleanField(default=False)),
                ("wt_overbought", models.BooleanField(default=False)),
                ("wt_momentum", models.FloatField(blank=True, null=True)),
                ("is_squeeze", models.BooleanField(default=False)),
                ("squeeze_released", models.BooleanField(default=False)),
                ("obv_confirmed", models.BooleanField(default=False)),
                ("rsi", models.FloatField(blank=True, null=True)),
                ("macd", models.FloatField(blank=True, null=True)),
                ("macd_signal", models.FloatField(blank=True, null=True)),
                ("macd_hist", models.FloatField(blank=True, null=True)),
                ("adx", models.FloatField(blank=True, null=True)),
                ("mfi", models.FloatField(blank=True, null=True)),
                ("sma5", models.FloatField(blank=True, null=True)),
                ("sma20", models.FloatField(blank=True, null=True)),
                ("sma120", models.FloatField(blank=True, null=True)),
                (
                    "deviation",
                    models.FloatField(
                        blank=True, null=True, verbose_name="20일선 이격도(%)"
                    ),
                ),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "verbose_name": "종목 최신 분석",
            },
        ),
        migrations.AlterField(
            model_name="stockanalysislatest",
            name="stock",
            field=models.OneToOneField(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="latest_analysis2",
                to="stock.stockmaster",
            ),
        ),
        migrations.AddIndex(
            model_name="stockdailychart",
            index=models.Index(fields=["-date"], name="stock_stock_date_9b94d3_idx"),
        ),
        migrations.AddField(
            model_name="stockanalysislatest2",
            name="signal_code",
            field=models.ForeignKey(
                db_column="signal_code",
                default="d01",
                on_delete=django.db.models.deletion.SET_DEFAULT,
                to="stock.signalcode2",
                verbose_name="시그널 코드",
            ),
        ),
        migrations.AddField(
            model_name="stockanalysislatest2",
            name="stock",
            field=models.OneToOneField(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="latest_analysis",
                to="stock.stockmaster",
            ),
        ),
        migrations.AddIndex(
            model_name="stockanalysislatest2",
            index=models.Index(
                fields=["priority", "signal_code"],
                name="stock_stock_priorit_b37dd4_idx",
            ),
        ),
        migrations.AddIndex(
            model_name="stockanalysislatest2",
            index=models.Index(
                fields=["signal_code"], name="stock_stock_signal__0f6e07_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="stockanalysislatest2",
            index=models.Index(
                fields=["is_squeeze", "squeeze_released"],
                name="stock_stock_is_sque_947b7c_idx",
            ),
        ),
        migrations.AddIndex(
            model_name="stockanalysislatest2",
            index=models.Index(
                fields=["updated_at"], name="stock_stock_updated_52ae58_idx"
            ),
        ),
    ]
