# Generated by Django 6.0.3 on 2026-04-25 14:31

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("stock", "0010_signalcode2_stockanalysislatest2_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="stockanalysislatest2",
            name="stock",
            field=models.OneToOneField(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="latest_analysis",
                to="stock.stockmaster",
                to_field="ticker",
            ),
        ),
    ]
