# Generated by Django 6.0.3 on 2026-04-27 12:52

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("stock", "0011_alter_stockanalysislatest2_stock"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="stockanalysislatest",
            options={"verbose_name": "종목 최신 분석"},
        ),
        migrations.AlterModelOptions(
            name="stockanalysislatest2",
            options={"verbose_name": "종목 최신 분석_v2"},
        ),
        migrations.CreateModel(
            name="CoinAnalysisLatest",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "interval",
                    models.CharField(
                        choices=[("1h", "1시간봉"), ("4h", "4시간봉")],
                        max_length=5,
                        verbose_name="봉 단위",
                    ),
                ),
                ("analyzed_at", models.DateTimeField(verbose_name="분석 시각")),
                (
                    "close_price",
                    models.DecimalField(
                        decimal_places=8, max_digits=30, verbose_name="종가"
                    ),
                ),
                ("volume", models.FloatField(verbose_name="거래량")),
                (
                    "vol_ratio",
                    models.FloatField(
                        blank=True, null=True, verbose_name="거래량 비율"
                    ),
                ),
                (
                    "change_rate",
                    models.FloatField(blank=True, null=True, verbose_name="등락률"),
                ),
                (
                    "signal",
                    models.CharField(
                        default="대기중", max_length=100, verbose_name="시그널 명칭"
                    ),
                ),
                ("priority", models.IntegerField(default=0, verbose_name="우선순위")),
                (
                    "action",
                    models.TextField(blank=True, null=True, verbose_name="대응 전략"),
                ),
                (
                    "supertrend_direction",
                    models.IntegerField(blank=True, null=True, verbose_name="ST 방향"),
                ),
                ("wt1", models.FloatField(blank=True, null=True)),
                ("wt2", models.FloatField(blank=True, null=True)),
                ("wt_cross_up", models.BooleanField(default=False)),
                ("wt_cross_down", models.BooleanField(default=False)),
                ("wt_oversold", models.BooleanField(default=False)),
                ("wt_overbought", models.BooleanField(default=False)),
                ("wt_momentum", models.FloatField(blank=True, null=True)),
                (
                    "is_squeeze",
                    models.BooleanField(default=False, verbose_name="응축 중"),
                ),
                (
                    "squeeze_released",
                    models.BooleanField(default=False, verbose_name="응축 돌파"),
                ),
                ("rsi", models.FloatField(blank=True, null=True)),
                ("macd", models.FloatField(blank=True, null=True)),
                ("macd_hist", models.FloatField(blank=True, null=True)),
                ("adx", models.FloatField(blank=True, null=True)),
                (
                    "obv_confirmed",
                    models.BooleanField(default=False, verbose_name="OBV 수급 확인"),
                ),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "signal_code",
                    models.ForeignKey(
                        db_column="signal_code",
                        default="d01",
                        on_delete=django.db.models.deletion.SET_DEFAULT,
                        to="stock.signalcode2",
                    ),
                ),
                (
                    "stock",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="coin_analysis",
                        to="stock.stockmaster",
                        to_field="ticker",
                    ),
                ),
            ],
            options={
                "verbose_name": "코인 분석 결과",
                "verbose_name_plural": "코인 분석 결과",
                "db_table": "coin_analysis_latest",
                "indexes": [
                    models.Index(
                        fields=["priority", "signal_code"],
                        name="coin_analys_priorit_bcb6c5_idx",
                    ),
                    models.Index(
                        fields=["stock", "interval"],
                        name="coin_analys_stock_i_032728_idx",
                    ),
                ],
                "constraints": [
                    models.UniqueConstraint(
                        fields=("stock", "interval"), name="unique_coin_interval"
                    )
                ],
            },
        ),
    ]
